# Generated by Django 5.1.4 on 2025-03-17 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorymodel',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='categorymodel',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
