# Generated by Django 5.1.4 on 2025-04-04 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_ordermodel_orderitemmodel'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='itemmodel',
            unique_together={('cart', 'product')},
        ),
    ]
