# Generated by Django 5.1.4 on 2025-04-08 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_itemmodel_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order_summary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=100)),
                ('payment_status', models.BooleanField(default=False)),
                ('order_item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.orderitemmodel')),
            ],
        ),
    ]
