# Generated by Django 5.1.4 on 2025-04-08 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_order_summary'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order_summary',
        ),
    ]
