# Generated by Django 5.1.4 on 2025-04-08 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_delete_order_summary'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order_summary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=100)),
                ('payment_status', models.BooleanField(default=False)),
                ('payment_id', models.CharField(blank=True, max_length=100, null=True)),
                ('total', models.FloatField()),
                ('data', models.DateField(auto_now_add=True)),
                ('order_item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.orderitemmodel')),
            ],
        ),
    ]
