# Generated by Django 5.2.5 on 2025-08-25 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_alter_ordermodel_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitemmodel',
            old_name='order_id',
            new_name='order',
        ),
        migrations.AlterField(
            model_name='orderitemmodel',
            name='quantity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='orderitemmodel',
            name='status',
            field=models.CharField(max_length=20),
        ),
    ]
